cmake_minimum_required(VERSION 3.12)

set(BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Comet/")

file(GLOB_RECURSE FOUND_FILES CONFIGURE_DEPENDS "${BASE_DIR}/*.h" "${BASE_DIR}/*.cpp")

source_group("COMET_FILES" FILES ${FOUND_FILES})

set(COMET_CLIENT
${FOUND_FILES}
)